"""METAENGINE Phase 28 — Autonomous Experiment Loop.

The engine autonomously: hypothesize → select experiment → execute →
record outcome → adjust selection → repeat. This is the closed-loop
self-improvement engine.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from .util import canonical_hash
from .information_gain_selector import InformationGainSelector


AUTONOMOUS_LOOP_VERSION = "METAENGINE-AUTONOMOUS-EXPERIMENT-LOOP-1"


@dataclass(frozen=True)
class Hypothesis:
    """A testable hypothesis generated by the autonomous loop."""
    hypothesis_id: str
    mechanism_ids: tuple[str, ...]
    rationale: str
    task_features: dict[str, float]
    hypothesis_hash: str

    def payload(self) -> dict[str, Any]:
        return {
            "hypothesis_id": self.hypothesis_id,
            "mechanism_ids": list(self.mechanism_ids),
            "rationale": self.rationale,
            "task_features": self.task_features,
            "truth_effect": "NONE",
        }


@dataclass(frozen=True)
class ExperimentOutcome:
    """Recorded outcome of an experiment."""
    experiment_id: str
    quality: float
    success: bool


class AutonomousExperimentLoop:
    """Autonomously generates hypotheses, selects experiments, and records outcomes.

    The loop:
    1. generate_hypothesis: from mechanism library + task features
    2. select_experiment: by information gain
    3. (external execution)
    4. record_outcome: quality + success
    5. Adjust selection based on recorded outcomes
    """

    def __init__(self, *, seed: int = 42):
        self._selector = InformationGainSelector()
        self._outcomes: list[ExperimentOutcome] = []
        self._seed = seed

    def generate_hypothesis(
        self,
        *,
        mechanism_library_ids: list[str],
        task_features: Mapping[str, float],
    ) -> Hypothesis:
        """Generate a testable hypothesis from the mechanism library."""
        # Select top 2 mechanisms by availability
        mechs = tuple(sorted(mechanism_library_ids[:2]))
        rationale = (
            f"Hypothesis: combining {len(mechs)} mechanisms "
            f"for task with complexity={task_features.get('complexity', 0.5):.2f}"
        )
        h = Hypothesis(
            hypothesis_id=f"hyp.{canonical_hash({'mechs': mechs, 'tf': dict(task_features)})[:12]}",
            mechanism_ids=mechs,
            rationale=rationale,
            task_features=dict(task_features),
            hypothesis_hash="",
        )
        return Hypothesis(**{**h.__dict__, "hypothesis_hash": canonical_hash(h.payload())})

    def select_experiment(
        self,
        candidates: list[dict[str, Any]],
        *,
        budget: float,
    ) -> list[dict[str, Any]]:
        """Select experiments by information gain, adjusted by past outcomes."""
        # Adjust expected_gain based on past outcomes
        adjusted = []
        for c in candidates:
            c_adj = dict(c)
            # If we have outcomes for similar experiments, adjust expected_gain
            matching = [o for o in self._outcomes if o.experiment_id.startswith(c["id"][:3])]
            if matching:
                avg_q = sum(o.quality for o in matching) / len(matching)
                c_adj["expected_gain"] = 0.5 * c.get("expected_gain", 0.5) + 0.5 * avg_q
            adjusted.append(c_adj)
        return self._selector.select(adjusted, budget=budget)

    def record_outcome(self, *, experiment_id: str, quality: float, success: bool) -> None:
        """Record the outcome of an experiment."""
        self._outcomes.append(ExperimentOutcome(
            experiment_id=experiment_id,
            quality=quality,
            success=success,
        ))

    def loop_hash(self) -> str:
        return canonical_hash(self.payload())

    def payload(self) -> dict[str, Any]:
        return {
            "loop_version": AUTONOMOUS_LOOP_VERSION,
            "outcome_count": len(self._outcomes),
            "seed": self._seed,
            "truth_effect": "NONE",
            "claim_ceiling": "AUTONOMOUS_LOOP_IS_EXPERIMENTAL_NOT_TRUTH",
        }
